### ISSUE TITLE
필라테스 ㄲ

### ISSUE THREAD

**Issue by tonyhan18** [mtak0235/DietDiary#1]
먹는것만 조절해도 쌉가능

**Comment by mtak0235** [comment]
여기서 이러시면 안됩니다 차한님.. 새로 시작하는 프로제긑 이슈1을 가져가시다니;;

**Comment by tonyhan18** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 배포 도와드릴까요?

**Comment by mtak0235** [comment]
됐어욬ㅋㅋㅋㅋㅋㅋㅋㅋ 배포 하다가  모르는거 생기면 귤하나 손에 쥐고 가겠습니닼ㅋㅋㅋㅋㅋㅋㅋ
