### ISSUE TITLE
MongoDB 사용법 

### ISSUE THREAD

**Issue by 20151883** [mtak0235/DietDiary#10]

**Comment by 20151883** [comment]
MongoDB 사용법을 잘 익혀서. 챗봇이랑 연동. 일단 에코 챗봇을 만들어 보는 정도까지 해보자.

**Comment by mtak0235** [comment]
huchoi - 공식문서 양이 너무 많아서, 필요할 때 보충해야겠다. 스프링이랑 mongodb연결했다.

**Comment by mtak0235** [comment]
mtak - 공식 문서 data modeling 부분까지 읽었는데 embeded 방식이 뭔지 잘 모르겠다. 그냥 document 가 document안에 하나 더 있을 뿐인데? 정규화 역정규화 인덱싱 부분 모르겠다. 
"데이터베이스 입문"이라는 책을 읽고, 트랜잭션과 동기화에 대한 고민이 깊어졌다

**Comment by mtak0235** [comment]
기본 학습을 끝냈고, 이후 추가 지식은 그때그때 보충한다.
