### ISSUE TITLE
gradle 기반으로 spring과 mongodb 연동하기

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/DietDiary#16]
그레이들이 메이븐보다 더 잘나가니까 쓴다.

**Comment by 20151883** [comment]
공식문서 참조
https://www.mongodb.com/compatibility/spring-boot
이 사이트는 maven을 사용하는데, 우리는 gradle을 사용하기로 했음.
참고: http://sagioto.github.io/maven2gradle/ (이 사이트에서 maven을 gradle로 바꿔줌)
