### ISSUE TITLE
간단한 챗봇 만들어보기

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/DietDiary#2]

**Comment by 20151883** [comment]
챗봇 만들어서 fulfillment 기능 써보는거까지 해봤습니다.

https://medium.com/@jwlee98/gcp-dialogflow-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B0%84%EB%8B%A8-%EC%B1%97%EB%B4%87-%EB%A7%8C%EB%93%A4%EA%B8%B0-514ea25e4961
(챗봇 만들기, 조금 자세한 설명)

https://cloud.google.com/dialogflow/es/docs/fulfillment-overview (fulfillment에 대한 공식문서)
(참고로 es랑 cx랑 공식문서가 나뉘어져있습니다. 저는 es instance 생성했는데, 공식문서는 cx에 대한거 보고 있다가 시간낭비했네요...)

fullfillment를 사용하기 위해선 https 사용해야만 해서, 사설 SSL 인증서 받아와서, nginx로 리버스프록시 써보는 방법도 해보고... 여러가지 삽질을 많이 했는데... 결국 실패했네요... 아마 사설 SSL 인증서 안되나봐요.....
그래서 공식SSL인증서를 사와야 할거 같은데.. 일단 나중으로 미뤘어요.

결국 유튭에 https://www.youtube.com/watch?v=7jTajujOTIA 좋은 영상을 찾을수 있었네요.
여기서 하는대로 따라하면 금방 fulfillment 사용해 볼수 있습니다. ngrok 이라는 걸 이용.
지금은 여기서 코드 좀 수정해보면서 연습해보는 중입니다.

블로그 정리용으로 잘 써서 여기에 붙여넣으려고 했는데, 정리해서 글 쓰는데에 시간이 많이 걸리네요;;
일단 제가 참고했던 사이트들만 임시적으로 올려놓을게요.

**Comment by mtak0235** [comment]
챗봇 만들어서 fullfillment(webhook, inline editor)기능 써보는 것을 했습니다.   배포 환경은 GCP이고 Firebase를 사용했습니다. 
integration은 web demo로 했습니다.  챗봇 내부 로직에 문제가 있어 생각대로 동작하지는않았습니다.
https://rubenchoi.tistory.com/33
(챗봇 만들기, 배포 및 slack 연동, react app연동)  👉실습한 레퍼런스
https://medium.com/@jwlee98/gcp-dialogflow-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B0%84%EB%8B%A8-%EC%B1%97%EB%B4%87-%EB%A7%8C%EB%93%A4%EA%B8%B0-514ea25e4961
(챗봇 만들기 및 integration)
https://chanos.tistory.com/entry/AI-Chatbot-%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5-%EC%B1%97%EB%B4%87%EC%9D%98-%EC%A0%95%EC%9D%98-%EC%A2%85%EB%A5%98-%ED%8A%B9%EC%A7%95?category=997301
(챗봇 종류 및 만들기)
https://codevkr.tistory.com/74?category=748958
(챗봇 만들기 및 카카오톡 연동)
https://m.blog.naver.com/bsgyo/221624724806
(integration 참조)

https://cloud.google.com/dialogflow/es/docs/integrations
빅스비로 integrate해보고 싶었는데, 기본적으로 제공되는게 아니라서 dialogflow api로 직접 만들어야 한다고 함.  아직 못해봄

chatbot builder : 가장 유명한 것은 ibm watson, chatfuel, dialogflow, (국내)kakao openbuilder, naver clova
 http://chatbotq.org/wp/?page_id=156

**Comment by mtak0235** [comment]
ngrok로 도메인 할당 받아서 fulfillment를 이용해 springboot 프로젝트와 연동하는 것을 성공함.
