### ISSUE TITLE
배포환경 조사해오기

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/DietDiary#3]

**Comment by 20151883** [comment]
https://extsdd.tistory.com/category/IT/AWS (aws EC2 인스턴스 생성부터 ssh 접속, 고정 IP 할당 받기과 같은 필수적인 내용들을 잘 설명)
일단 여기에 나와있는대로 따라해봤는데, aws ec2 금방 만들수있었어요. 
ssh로 ec2 인스턴스에 접속해서 nginx 띄우고 node.js 서비스 켠 다음에, 외부 브라우저에서 이 서비스에 접속해보는 거 까지 실습해 보았어요.

일단 참고한 사이트만 올려놓고, 나중에 블로그용으로 잘 정리되면 다시 올리도록 하겠습니다.

**Comment by mtak0235** [comment]
`스프링부트와 aws로 혼자 구현하는 서비스`라는 책에서 aws ec2로 서버 환경 만들고, 데이터베이스 환경 만들고(aws rds) 프로젝트 배포하는 부분을 공부했습니다.

챗봇 실습 예제들 중 gcp로 dialogflow로 만들 챗봇을 배포하는 예제가 많았는데, dialogflow가 gcp가 제공하는 챗봇 api라서 그런 것 같습니다. 실습 예제에서 firebase라는 것을 썼는데, 딱히 데이터베이스로 쓴 것은 아닌 것 같고 웹앱을 만들기 위한 용도라고 합니다.  
어렵네욥..(주륵

**Comment by mtak0235** [comment]
aws ec2에 배포
