### ISSUE TITLE
웹으로 휴대용 기기에 PUSH알람을 줄 수 있나요?

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/DietDiary#4]

**Comment by 20151883** [comment]
https://www.youtube.com/watch?v=2zHqTjyfIY8&t=925s
(이 영상에서 나오는 대로 따라하면 push 알람을 보낼수 있습니다)

그런데 문제가 있는데, 
사용자가 윈도우 컴퓨터 + edge브라우저로 사이트에 접속한 상황에서는 push 알람이 잘 보내집니다.
사용자가 윈도우 컴퓨터 + chrome브라우저로 사이트에 접속한 상황에서는 어떤 조치를 취해줘야지 push 알람을 보낼수있습니다.
사용자가 맥 컴퓨터 + chrome 브라우저로 사이트에 접속한 상황에서는 어떤 조치를 취해도 push 알람을 보낼수 없습니다.
사용자가 맥 컴퓨터 + safari 브라우저로 사이트에 접속한 상황에서는 어떤 조치를 취해도 push 알람을 보낼수 없습니다.

브라우저 마다 되는게 있고, 안되는게 있고.... 컴퓨터 os마다 되는게 있고, 안되는게 있고... 이런 문제가 있네요.

**Comment by mtak0235** [comment]
>> 아직 해당 이슈를 진행하지 못했습니다ㅠ
>>보내주신 영상 확인했습니다! 보면서 든 생각은, 이벤트 기반으로 만드신 부분은 spring batch로 바꾸면 될 것 같은데 생각해보니 굳이 web에서 알람을 보낼 필요가 없지 않을까요? 저희 서버에서 바로 알람을 클라이언트(ex.구글 어시스턴트)로 보내면 되지 않을까 생각합니다. (시스템 설계를 하면 각이 나오지 않을까 생각합니다)

**Comment by mtak0235** [comment]
최소 기능이 아니므로 미룬다.
